name = "mctc-lib"
version = "0.5.0"
license = "Apache-2.0"
maintainer = ["@awvwgk"]
author = ["Sebastian Ehlert"]
copyright = "2020-2025 Sebastian Ehlert"
description = "Modular computation tool chain library"
keywords = ["computational-chemistry", "io"]

[dependencies]
jonquil.git = "https://github.com/toml-f/jonquil.git"
jonquil.tag = "v0.3.0"
toml-f.git = "https://github.com/toml-f/toml-f.git"
toml-f.tag = "v0.4.3"

[[executable]]
name = "mctc-convert"
