name = "mctc-lib"
version = "0.4.1"
license = "Apache-2.0"
maintainer = ["@awvwgk"]
author = ["Sebastian Ehlert"]
copyright = "2020-2024 Sebastian Ehlert"
description = "Modular computation tool chain library"
keywords = ["computational-chemistry", "io"]

[dependencies]
jonquil.git = "https://github.com/toml-f/jonquil.git"

[[executable]]
name = "mctc-convert"
